<?xml version="1.0" encoding="utf-8"?><Database Name="CaffeBase" Class="CaffeDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\App_data\CaffeBase.mdf;Integrated Security=True" SettingsObjectName="MGRMikolajczuk.Properties.Settings" SettingsPropertyName="CaffeBaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="Id_user" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="User_Order" Member="Orders" ThisKey="Id_user" OtherKey="Id_User" Type="Order" />
    </Type>
  </Table>
  <Table Name="dbo.Products" Member="Products">
    <Type Name="Product">
      <Column Name="Id_Product" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Product_OrderItem" Member="OrderItems" ThisKey="Id_Product" OtherKey="Id_Product" Type="OrderItem" />
    </Type>
  </Table>
  <Table Name="dbo.Orders" Member="Orders">
    <Type Name="Order">
      <Column Name="Id_Order" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Sum" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Id_User" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Order_OrderItem" Member="OrderItems" ThisKey="Id_Order" OtherKey="Id_Order" Type="OrderItem" />
      <Association Name="User_Order" Member="User" ThisKey="Id_User" OtherKey="Id_user" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderItem" Member="OrderItems">
    <Type Name="OrderItem">
      <Column Name="Id_OrderItem" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Id_Order" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id_Product" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Order_OrderItem" Member="Order" ThisKey="Id_Order" OtherKey="Id_Order" Type="Order" IsForeignKey="true" />
      <Association Name="Product_OrderItem" Member="Product" ThisKey="Id_Product" OtherKey="Id_Product" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
</Database>